version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: keycloak
    environment:
      KC_HTTP_PORT: 8181
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloakdb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8181:8181
    volumes:
      - ./keycloak-data:/opt/keycloak/data

  keycloakdb:
    image: mysql:8.0
    container_name: keycloakdb
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
